version: "3.9"
services:
  data_collector:
    build: 
      context: containers/data_collector
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: .
        target: /bigipreport
volumes:
  underlay:
  .: