version: "3.9"
services:
  frontend:
    image: bigipreport/frontend
    volumes:
      - type: volume
        source: .
        target: /bigipreport
        read_only: true
      - type: volume
        source: underlay
        target: /usr/share/nginx/html
        read_only: true
volumes:
  underlay:
  .: